name: Extract Rootfs

on:
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Download openwrt.img.xz
        run: wget -O openwrt.img.xz https://atdxcdn.eu.org/0:/OpenWRT/OpenWrt_s905x_23.05.3_Clash-Wall-HG680P-14.07.2024_wifi_off.img.xz
        
      - name: Extract openwrt.img.xz
        run: xz -d openwrt.img.xz
        
      - name: Extract rootfs
        run: |
          mkdir rootfs
          sudo mount -o loop,offset=1048576 openwrt.img rootfs
          sudo tar czf rootfs.tar.gz -C rootfs .
          sudo umount rootfs
          rmdir rootfs
      
      - name: Upload rootfs.tar.gz artifact
        uses: actions/upload-artifact@v2
        with:
          name: rootfs-tarball
          path: rootfs.tar.gz
