name: Extract and Upload RootFS

on:
  workflow_dispatch: # Memungkinkan Anda untuk memicu workflow secara manual

jobs:
  extract-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Drive API
        run: |
          # Install required tools
          sudo apt-get update
          sudo apt-get install -y wget xz-utils

      - name: Download file from Google Drive
        env:
          GOOGLE_DRIVE_TOKEN: ${{ secrets.GOOGLE_DRIVE_TOKEN }} # Token akses Google Drive Anda
        run: |
          FILE_ID="1LPzDblSeEZN-vUHh029AffkFCdffc78r" # Ganti dengan ID file Google Drive Anda
          FILE_NAME="file.img.xz" # Nama file yang diunduh

          # Unduh file menggunakan Google Drive API
          wget --header="Authorization: Bearer ${GOOGLE_DRIVE_TOKEN}" \
               "https://www.googleapis.com/drive/v3/files/${FILE_ID}?alt=media" \
               -O "${FILE_NAME}"

      - name: Extract rootfs using dd
        run: |
          # Install required tools
          sudo apt-get install -y fdisk

          # Ekstrak file .img.xz
          xz -d "${FILE_NAME}"
          IMG_FILE="${FILE_NAME%.xz}" # Nama file setelah xz dihapus

          # Temukan offset partisi rootfs, misalnya partisi 2
          ROOTFS_START=$(fdisk -l "${IMG_FILE}" | grep '^/dev' | awk '{print $2}' | sed 's/[^0-9]*//g' | head -n 1)

          if [ -z "$ROOTFS_START" ]; then
            echo "Unable to find the partition start. Please check your image."
            exit 1
          fi

          # Ekstrak rootfs
          dd if="${IMG_FILE}" of="rootfs.img" bs=512 skip="${ROOTFS_START}" status=progress

      - name: Get file metadata
        id: metadata
        env:
          GOOGLE_DRIVE_TOKEN: ${{ secrets.GOOGLE_DRIVE_TOKEN }} # Token akses Google Drive Anda
        run: |
          FILE_ID="1LPzDblSeEZN-vUHh029AffkFCdffc78r" # Ganti dengan ID file Google Drive Anda

          # Ambil metadata file
          METADATA=$(curl -s -H "Authorization: Bearer ${GOOGLE_DRIVE_TOKEN}" \
                          "https://www.googleapis.com/drive/v3/files/${FILE_ID}?fields=name")
          FILE_NAME=$(echo "${METADATA}" | jq -r '.name')
          echo "FILE_NAME=${FILE_NAME}" >> $GITHUB_ENV

      - name: Compress rootfs to tar.gz
        run: |
          tar -czvf "${FILE_NAME%.xz}-rootfs.tar.gz" rootfs.img

      - name: Upload rootfs to Google Drive
        env:
          GOOGLE_DRIVE_TOKEN: ${{ secrets.GOOGLE_DRIVE_TOKEN }} # Token akses Google Drive Anda
        run: |
          FILE_PATH="${FILE_NAME%.xz}-rootfs.tar.gz"
          FILE_NAME="${FILE_NAME%.xz}-rootfs.tar.gz"
          FOLDER_ID="1YHEODaFpIJbrsnuu2SoWgqSjrZPkTVzB" # ID folder tujuan di Google Drive

          # Unggah file menggunakan Google Drive API
          curl -X POST -L \
               -H "Authorization: Bearer ${GOOGLE_DRIVE_TOKEN}" \
               -F "metadata={name : '${FILE_NAME}', parents: ['${FOLDER_ID}']};type=application/json;charset=UTF-8" \
               -F "file=@${FILE_PATH};type=application/gzip" \
               "https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart"
