name: Rootfs Gdrive

on:
  workflow_dispatch:

jobs:
  extract-rootfs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install required tools
      run: |
        sudo apt-get update
        sudo apt-get install -y wget xz-utils fdisk

    - name: Download file from Google Drive
      env:
        GOOGLE_DRIVE_ACCESS_TOKEN: ${{ secrets.GDRIVE_TOKEN }}
      run: |
        # ID file Google Drive (Gantilah dengan ID file yang sesuai)
        FILE_ID="1LPzDblSeEZN-vUHh029AffkFCdffc78r"
        FILE_NAME="openwrt.img.xz"

        # URL untuk mengunduh file
        DOWNLOAD_URL="https://www.googleapis.com/drive/v3/files/${FILE_ID}?alt=media"

        # Mengunduh file
        curl -L -o $FILE_NAME \
          -H "Authorization: Bearer $GOOGLE_DRIVE_ACCESS_TOKEN" \
          $DOWNLOAD_URL

    - name: Extract OpenWRT image
      run: xz -d openwrt.img.xz

    - name: Find rootfs partition offset
      id: find-offset
      run: |
        # Find the offset of the rootfs partition
        ROOTFS_OFFSET=$(fdisk -l openwrt.img | grep Linux | awk '{print $2}')
        echo "ROOTFS_OFFSET=$ROOTFS_OFFSET" >> $GITHUB_ENV

    - name: Extract rootfs using dd
      run: |
        # Convert the offset to bytes (assuming sector size is 512 bytes)
        OFFSET_BYTES=$(($ROOTFS_OFFSET * 512))
        # Extract the rootfs partition
        dd if=openwrt.img bs=512 skip=$ROOTFS_OFFSET of=rootfs.img

    - name: Mount the rootfs image and create tar.gz
      run: |
        sudo mkdir /mnt/rootfs
        sudo mount -o loop rootfs.img /mnt/rootfs
        sudo tar -czvf rootfs.tar.gz -C /mnt/rootfs .
        sudo umount /mnt/rootfs

    - name: Upload rootfs.tar.gz to Google Drive
      env:
        GDRIVE_TOKEN: ${{ secrets.GDRIVE_TOKEN }}
      run: |
        # ID folder Google Drive untuk mengupload file
        PARENT_FOLDER_ID="1YHEODaFpIJbrsnuu2SoWgqSjrZPkTVzB"
        FILE_NAME="rootfs.tar.gz"
          
        # Upload file ke Google Drive
        curl -X POST -L \
          -H "Authorization: Bearer $GOOGLE_DRIVE_ACCESS_TOKEN" \
          -F "metadata={name : '$FILE_NAME', parents : ['$PARENT_FOLDER_ID']};type=application/json;charset=UTF-8" \
          -F "file=@$FILE_NAME;type=application/octet-stream" \
          "https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart"
