name: Get Google Drive Token

on:
  workflow_dispatch:

jobs:
  get-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Generate authorization URL
        id: generate-url
        run: |
          echo "from google_auth_oauthlib.flow import InstalledAppFlow" > generate_url.py
          echo "flow = InstalledAppFlow.from_client_config({" >> generate_url.py
          echo "  'installed': {" >> generate_url.py
          echo "    'client_id': '${{ secrets.GDRIVE_CLIENT_ID }}'," >> generate_url.py
          echo "    'client_secret': '${{ secrets.GDRIVE_CLIENT_SECRET }}'," >> generate_url.py
          echo "    'redirect_uris': ['urn:ietf:wg:oauth:2.0:oob', 'http://localhost']" >> generate_url.py
          echo "  }" >> generate_url.py
          echo "}, ['https://www.googleapis.com/auth/drive.file'])" >> generate_url.py
          echo "auth_url, _ = flow.authorization_url(prompt='consent')" >> generate_url.py
          echo "print(auth_url)" >> generate_url.py
          python generate_url.py > auth_url.txt
        shell: bash

      - name: Output authorization URL
        run: |
          echo "Authorization URL: $(cat auth_url.txt)"
          echo "::set-output name=auth_url::$(cat auth_url.txt)"
        id: auth-url-output

      - name: Request authorization
        run: echo "Please visit the following URL to authorize the application: ${{ steps.auth-url-output.outputs.auth_url }}"

      - name: Wait for authorization code
        run: read -p "Enter the authorization code: " auth_code
        id: wait-for-auth-code
        shell: bash

      - name: Exchange authorization code for tokens
        run: |
          echo "from google_auth_oauthlib.flow import InstalledAppFlow" > exchange_code.py
          echo "flow = InstalledAppFlow.from_client_config({" >> exchange_code.py
          echo "  'installed': {" >> exchange_code.py
          echo "    'client_id': '${{ secrets.GDRIVE_CLIENT_ID }}'," >> exchange_code.py
          echo "    'client_secret': '${{ secrets.GDRIVE_CLIENT_SECRET }}'," >> exchange_code.py
          echo "    'redirect_uris': ['urn:ietf:wg:oauth:2.0:oob', 'http://localhost']" >> exchange_code.py
          echo "  }" >> exchange_code.py
          echo "}, ['https://www.googleapis.com/auth/drive.file'])" >> exchange_code.py
          echo "flow.fetch_token(code='${{ steps.wait-for-auth-code.outputs.auth_code }}')" >> exchange_code.py
          echo "creds = flow.credentials" >> exchange_code.py
          echo "print('Access Token:', creds.token)" >> exchange_code.py
          echo "print('Refresh Token:', creds.refresh_token)" >> exchange_code.py
          python exchange_code.py
        shell: bash
